"""empty message

Revision ID: 65237cb9e106
Revises: 
Create Date: 2019-02-18 20:37:01.004758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65237cb9e106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root', sa.String(length=2), nullable=False),
    sa.Column('major', sa.String(length=500), nullable=True),
    sa.Column('minor', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inversions')
    op.drop_table('chords')
    op.drop_table('sheets')
    # ### end Alembic commands ###
